### ISSUE TITLE
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"

### ISSUE THREAD

**Issue by phpclub** [ZPascal/acme-dns#82]
sqlite3 faild 

acme-dns.service: Main process exited, code=exited, status=1/FAILURE
Jul 17 00:27:08 fra systemd[1]: acme-dns.service: Failed with result 'exit-code'.
Jul 17 00:27:08 fra systemd[1]: acme-dns.service: Scheduled restart job, restart counter is at 4.
Jul 17 00:27:08 fra systemd[1]: Stopped Limited DNS server with RESTful HTTP API to handle ACME DNS challenges easily and securely.
Jul 17 00:27:08 fra systemd[1]: Started Limited DNS server with RESTful HTTP API to handle ACME DNS challenges easily and securely.
Jul 17 00:27:08 fra acme-dns[4806]: time="2024-07-17T00:27:08+03:00" level=info msg="Using config file" file=/etc/acme-dns/config.cfg
Jul 17 00:27:08 fra acme-dns[4806]: time="2024-07-17T00:27:08+03:00" level=error msg="Error in DB upgrade" error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"
Jul 17 00:27:08 fra acme-dns[4806]: time="2024-07-17T00:27:08+03:00" level=error msg="Could not open database [Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub]"
Jul 17 00:27:08 fra systemd[1]: acme-dns.service: Main process exited, code=exited, status=1/FAILURE
Jul 17 00:27:08 fra systemd[1]: acme-dns.service: Failed with result 'exit-code'.
Jul 17 00:27:08 fra systemd[1]: acme-dns.service: Scheduled restart job, restart counter is at 5.
Jul 17 00:27:08 fra systemd[1]: Stopped Limited DNS server with RESTful HTTP API to handle ACME DNS challenges easily and securely.
Jul 17 00:27:08 fra systemd[1]: acme-dns.service: Start request repeated too quickly.
Jul 17 00:27:08 fra systemd[1]: acme-dns.service: Failed with result 'exit-code'.

**Comment by ZPascal** [comment]
@phpclub Do you need it only on Linux systems?

**Comment by ZPascal** [comment]
@phpclub #83 fixes the error. I'm closing the issue.

**Comment by phpclub** [comment]
> @phpclub #83 fixes the error. I'm closing the issue.

Thx, bro
